run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic
    - revive
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming

issues:
  exclude-use-default: false
