FROM golang:1.26-alpine

WORKDIR /app

ENV GOTOOLCHAIN=auto

RUN apk add --no-cache git make

RUN --mount=type=cache,target=/go/pkg/mod \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

