export * from '@/features/auth/routes/login'
export * from '@/features/auth/routes/register'
export * from '@/features/auth/routes/auth'
export * from '@/features/auth/routes/forgot'
export * from '@/features/auth/routes/reset'