basePath: /api/v1
definitions:
  api.BadReqResponse:
    properties:
      code:
        type: string
      details:
        items:
          $ref: '#/definitions/api.FieldError'
        type: array
      message:
        type: string
    type: object
  api.DataResponse:
    properties:
      data: {}
    type: object
  api.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  api.FieldError:
    properties:
      field:
        type: string
      tags:
        type: string
    type: object
  api.MessageResponse:
    properties:
      message:
        type: string
    type: object
  api.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      meta: {}
    type: object
  api.UnauthorizedResponse:
    properties:
      message:
        type: string
    type: object
  auth.ForgotPasswordRequest:
    properties:
      email:
        maxLength: 254
        type: string
    required:
    - email
    type: object
  auth.LoginUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      password:
        maxLength: 70
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.MeResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      id:
        type: string
      role:
        type: string
      status:
        type: string
    type: object
  auth.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  auth.RegisterUserRequest:
    properties:
      email:
        maxLength: 254
        type: string
      password:
        maxLength: 70
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.ResendOTPRequest:
    properties:
      email:
        maxLength: 254
        type: string
    required:
    - email
    type: object
  auth.ResetTokenRequest:
    properties:
      password:
        maxLength: 70
        minLength: 8
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
  auth.TokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  auth.VerifyOTPRequest:
    properties:
      code:
        type: string
      email:
        maxLength: 254
        type: string
    required:
    - code
    - email
    type: object
  product.CreateProductRequest:
    properties:
      currency:
        type: string
      description:
        type: string
      price:
        type: integer
      short_description:
        type: string
      sku:
        type: string
      slug:
        type: string
      status:
        type: string
      title:
        type: string
    required:
    - price
    - slug
    - status
    - title
    type: object
  product.ProductResponse:
    properties:
      created_at:
        type: string
      currency:
        type: string
      description:
        type: string
      id:
        type: string
      price:
        type: integer
      short_description:
        type: string
      sku:
        type: string
      slug:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: This is the Prim API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Prim API
  version: "1.0"
paths:
  /auth/forget-password:
    post:
      consumes:
      - application/json
      description: Email reset password link
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/auth.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.UnauthorizedResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Email reset password link
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user by email and password
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/auth.TokensResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Login user by email and password
      tags:
      - Auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: fetch session user data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/auth.MeResponse'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: fetch session user data
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Rotate refresh token and issue new access and refresh tokens.
      parameters:
      - description: Refresh Token
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/auth.TokensResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.UnauthorizedResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Rotate refresh token and issue new access and refresh tokens.
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User Credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
  /auth/resend-otp:
    post:
      consumes:
      - application/json
      description: resend email otp
      parameters:
      - description: Email and OTP
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/auth.ResendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: resend email otp
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password using a reset token
      parameters:
      - description: Password and Reset Token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.ResetTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.UnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Reset password using a reset token
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: Verify a user's email using a one-time verification code.
      parameters:
      - description: Email and OTP
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.UnauthorizedResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Verify a user's email address
      tags:
      - Auth
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/api.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/product.ProductResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create a new product
      tags:
      - Products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Get a product by passing it's id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadReqResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get a product by id
      tags:
      - Products
security:
- BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
